predict:
  SIZE: 1024
  dir_folder: /Users/maksimfomin/IT/DS_practice/4.CV/1.Similar_to_actor
  load:
    path:
      load_men: data/raw/men
      load_women: data/raw/women
      write_men: data/processed/men
      write_women: data/processed/women
  model_lr: LogisticRegression
  path_load: data/test_img/test_image.jpeg
  path_model: model/model.pkl
  random_state: 10
  model_lr_men: LogisticRegression_men
  model_lr_women: LogisticRegression_women
  version_lr_men: 7
  version_lr_women: 6
train:
  dir_folder: /Users/maksimfomin/IT/DS_practice/4.CV/1.Similar_to_actor
  key_load_img: false
  load:
    images:
      SIZE: 256
      actors:
      - Adam Sandler
      - Adrien Brody
      - Al Pacino
      - Anthony Hopkins
      - Antonio Banderas
      - Arnold Schwarzenegger
      - Ashton Kutcher
      - Ben Stiller
      - Ben Foster
      - Ben Affleck
      - Brad Pitt
      - Bruce Willis
      - Charlie Sheen
      - Christian Bale
      - Christoph Waltz
      - Clint Eastwood
      - Colin Firth
      - Cuba Gooding Jr.
      - Daniel Day-Lewis
      - Dennis Quaid
      - Denzel Washington
      - Donald Sutherland
      - Dustin Hoffman
      - Edward Norton
      - Gary Oldman
      - George Clooney
      - Gerard Butler
      - Harrison Ford
      - Hugh Grant
      - Hugh Jackman
      - Ian Holm
      - Jack Black
      - Jack Nicholson
      - Jake Gyllenhaal
      - James McAvoy
      - Jamie Foxx
      - Jeff Goldblum
      - Jeff Bridges
      - Jeremy Renner
      - Jim Carrey
      - John Travolta
      - John Malkovich
      - Johnny Depp
      - Jude Law
      - Keanu Reeves
      - Kevin Spacey
      - Leonardo DiCaprio
      - Liam Neeson
      - Martin Sheen
      - Matt Damon
      - Matthew McConaughey
      - Mel Gibson
      - Michael Douglas
      - Morgan Freeman
      - Nicolas Cage
      - Orlando Bloom
      - Owen Wilson
      - Philip Seymour Hoffman
      - Robert De Niro
      - Russell Crowe
      - Ryan Gosling
      - Sam Rockwell
      - Sam Neill
      - Samuel L. Jackson
      - Stephen Lang
      - Steve Martin
      - Steve Carell
      - Sylvester Stallone
      - Tobey Maguire
      - Tom Cruise
      - Tom Hanks
      - Tommy Lee Jones
      - Will Smith
      - Willem Dafoe
      actresses:
      - Alicia Vikander
      - Amy Adams
      - Andie MacDowell
      - Angelina Jolie
      - Anne Hathaway
      - Cameron Diaz
      - Carey Mulligan
      - Cate Blanchett
      - Catherine Zeta-Jones
      - Charlize Theron
      - Claire Forlani
      - Demi Moore
      - Drew Barrymore
      - Elizabeth Taylor
      - Emma Stone
      - Eva Mendes
      - Frances McDormand
      - Gwyneth Paltrow
      - Halle Berry
      - Hilary Swank
      - Jennifer Aniston
      - Jessica Biel
      - Jessica Chastain
      - Jodie Foster
      - Julia Roberts
      - Julianne Moore
      - Juliette Binoche
      - Kate Winslet
      - Keira Knightley
      - Kim Basinger
      - Kirsten Dunst
      - Kristin Scott Thomas
      - Lupita Nyong'o
      - Maggie Gyllenhaal
      - Marion Cotillard
      - Meg Ryan
      - Megan Fox
      - Melanie Laurent
      - Meryl Streep
      - Michelle Pfeiffer
      - Milla Jovovich
      - Naomi Watts
      - Natalie Portman
      - Natasha Henstridge
      - Nicole Kidman
      - Nina Dobrev
      - Octavia Spencer
      - Penélope Cruz
      - Rachel McAdams
      - Reese Witherspoon
      - Renée Zellweger
      - Rosamund Pike
      - Sandra Bullock
      - Scarlett Johansson
      - Sharon Stone
      - Sigourney Weaver
      - Susan Sarandon
      - Vera Farmiga
      - Viola Davis
      - Whoopi Goldberg
      - Winona Ryder
      limit_load: 15
    path:
      load_men: data/raw/men
      load_women: data/raw/women
      write_men: data/processed/men
      write_women: data/processed/women
  model_lr_men: LogisticRegression_men
  model_lr_women: LogisticRegression_women
  name_experiment: experiment_sa_3
  path_model: model/model.pkl
  random_state: 10
  test_size: 0.25
